### ISSUE TITLE
Add a function to check the input of the encryption "secret"

### ISSUE THREAD

**Issue by nicolasbock** [video-game-coding-club/crypto-webpage#54]
For the Caesar Cipher the encryption secret is an integer `[0, 25]` (at least for ASCII and English). The "encrypt" function should verify that the input is within that range and of the correct type before doing anything else. Add such a check.

**Comment by zmedin** [comment]
Dad's question: If the secret is "2", do we want that to mean shift the letter 2 spaces to the right (this makes more sense to me alphabetically than shifting to the left)? Do we want to allow [-25,25] so we can shift both left and right, or do you just have to calculate 26-2 = 24 to shift the other way?

**Comment by nicolasbock** [comment]
Yes, I think a range of `[-25, 25]` sounds good. Also, don't forget to check that the input is actually an integer first.

**Comment by zmedin** [comment]
Now the secret key can be any integer. This just checks if the key is an integer.

**Comment by nicolasbock** [comment]
Ok that's true. Let's add a check to this function then that the secret is within the proper range.
